//LOGIN TYPES
export const USER_LOGIN_VALUE = "USER_LOGIN_VALUE";
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGIN_EMPTY = 'USER_LOGIN_EMPTY';


export const SET_ROUTER = 'SET_ROUTER';