//LOGIN TYPES
export const USER_LOGIN_VALUE = "USER_LOGIN_VALUE";
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGIN_EMPTY = 'USER_LOGIN_EMPTY';

//REGISTER TYPES
export const USER_REGISTER_VALUE = "USER_REGISTER_VALUE";
export const USER_REGISTER_EMPTY = "USER_REGISTER_EMPTY";
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';

//USER PROFILE TYPES
export const USER_PROFILE_VALUE = "USER_PROFILE_VALUE";
export const USER_PROFILE = 'USER_PROFILE';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAILURE = 'USER_PROFILE_FAILURE';
export const USER_PROFILE_EMPTY = 'USER_PROFILE_EMPTY';

//USER CHANGE PASSWORD
export const CHANGE_PASSWORD_VALUE = "CHANGE_PASSWORD_VALUE";
export const CHANGE_PASSWORD_EMPTY = "CHANGE_PASSWORD_EMPTY";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

//USER FORGOT PASSWORD
export const USER_FORGOT_EMAIL = "SET_FORGOT_EMAIL";
export const SET_FORGOT_EMPTY = "SET_FORGOT_EMPTY";
export const USER_FORGOT = 'USER_FORGOT';
export const USER_FORGOT_SUCCESS = 'USER_FORGOT_SUCCESS';
export const USER_FORGOT_FAILURE = 'USER_FORGOT_FAILURE';

export const SET_ROUTER = 'SET_ROUTER';